version: '3'

services:
  grpc_server:
    build:
      context: .
      dockerfile: docker/grpc-server/Dockerfile
    container_name: grpc_server
    ports:
      - "8070:8070"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=simple_auth
      - DB_USERNAME=local
      - DB_PASSWORD=local
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - GRPC_SERVER_ADDR=:8070

  http_server:
    build:
      context: .
      dockerfile: ./docker/http-server/Dockerfile
    container_name: http_server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=simple_auth
      - DB_USERNAME=local
      - DB_PASSWORD=local
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - HTTP_SERVER_ADDR=:8080
      - GRPC_SERVER_ADDR=grpc_server:8070

  integration-tests:
    build:
      context: .
      dockerfile: ./docker/integration-tests/Dockerfile
    container_name: integration-tests
    depends_on:
      - grpc_server
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=simple_auth
      - DB_USERNAME=local
      - DB_PASSWORD=local
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - GRPC_SERVER_ADDR=grpc_server:8070

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=simple_auth
      - LC_ALL= C.UTF-8
